### ISSUE TITLE
How to solve `xml.etree.ElementTree.ParseError`?

### ISSUE THREAD

**Issue by yippp** [mattbierbaum/arxiv-public-datasets#9]
When I run the step Bulk download of ArXiv PDFs, I meet an error:
`python bin/pdfdownload.py /database/arxiv/manifest-index-v0.2.0-2019-03-01.json.gz
2020-09-03 11:26:19,672 - botocore.credentials - INFO: Found credentials in shared credentials file: ~/.aws/credentials
Traceback (most recent call last):
  File "bin/pdfdownload.py", line 6, in <module>
    manifest = s3_bulk_download.get_manifest(out)
  File "/database/arxiv/arxiv-public-datasets-0.2.0/arxiv_public_data/s3_bulk_download.py", line 135, in get_manifest
    return parse_manifest(manifest)
  File "/database/arxiv/arxiv-public-datasets-0.2.0/arxiv_public_data/s3_bulk_download.py", line 152, in parse_manifest
    root = ET.fromstring(manifest)
  File "/home/joshua/miniconda3/envs/arxivdataset/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0`

Could you guys tell me how to solve this problem?

**Comment by colinclement** [comment]
It looks like you're trying to provide the manifest as the `.json.gz` file from the 2.0 RELEASE. This is not an XML manifest file, which is what the command expects, but a JSON file containing a dictionary mapping tarballs to the specific arXiv PDFs in the state in which we downloaded them. If you remove that part of the command, i.e. invoke `python bin/pdfdownload.py` it will automatically retrieve the manifest for you from AWS, and then download it all as desired.

**Comment by colinclement** [comment]
@yippp can you confirm whether your issue is solved, and if so, close this issue?
